server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  ##数据源
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:oracle
    username: kab
    password: 123456
  ##thymeleaf视图解析器
  thymeleaf:
    mode: LEGACYHTML5
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html

