spring:
  ##数据源
  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:oracle
    username: kab
    password: 123456
  ##thymeleaf视图解析器
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/
    suffix: .html

